<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2022/23</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. Manuel J. Castro y Francisco J. Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Práctica número 1</span>
    </b></span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Para el <b>desarrollo de las prácticas de esta asignatura</b> usaremos de forma habitual la biblioteca <span style="font-family: Courier">NumPy</span>.
    <br>
    <span style="font-family: Courier">NumPy</span> (<i>Numerical Python</i>) es una biblioteca de código abierto de <span style="font-family: Courier">Python</span> que se utiliza en casi todos los campos de la ciencia y la ingeniería. Es el estándar universal para trabajar con datos numéricos en <span style="font-family: Courier">Python</span> y es el núcleo de los sistemas científicos de <span style="font-family: Courier">Python</span> y <span style="font-family: Courier">PyData</span>.
    <br>
    La biblioteca <span style="font-family: Courier">NumPy</span> permite trabajar con <b>matrices multidimensionales homogéneas</b> y proporciona una enorme <b>biblioteca de funciones matemáticas</b> de alto nivel que garantizan cálculos eficientes con vectores y matrices.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Todas las prácticas que realicemos deben comenzar con las instrucciones que siguen a continuación que permiten utilizar la codificación <span style="font-family: Courier">utf-8</span> (uso de tildes y otros caracteres especiales) y usar las funciones definidas en los módulos <span style="font-family: Courier">numpy</span> y <span style="font-family: Courier">numpy.linalg</span>, donde se encuentran la mayoría de los comandos utilizados.
    </span></div>

In [1]:
# -*- coding: utf-8 -*-
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Las <b>variables</b> que utilizamos (elementos de los vectores y las matrices) pueden ser <b>enteras</b>, <b>reales</b> (caracterizadas por la presencia del punto decimal o por el uso de la notación científica) o <b>complejas</b> (la unidad imaginaria se designa por <span style="font-family: Courier">j</span>, y debe ir precedida por la parte imaginaria del número complejo sin espacio intermedio); el <b>tipo</b> de la variable se obtiene con la función <span style="font-family: Courier">type()</span>. Todo número entero se puede convertir en real con la función <span style="font-family: Courier">float()</span>, mientras que todo número entero o real se puede convertir en complejo con la función <span style="font-family: Courier">complex()</span>. Respecto a los números complejos están disponibles, entre otras, las funciones <span style="font-family: Courier">real()</span>, <span style="font-family: Courier">imag()</span>, <span style="font-family: Courier">abs()</span>, <span style="font-family: Courier">angle()</span>, <span style="font-family: Courier">conj()</span> y <span style="font-family: Courier">exp()</span>, todas ellas con un significado obvio.
    </span></div>

In [2]:
# Tipos de variables.
i = 4
print("Entero: ", i, " de tipo ", type(i))
print("Real: ", float(i), " de tipo ", type(float(i)))
print("Complejo: ", complex(i), " de tipo ", type(complex(i)))

Entero:  4  de tipo  <class 'int'>
Real:  4.0  de tipo  <class 'float'>
Complejo:  (4+0j)  de tipo  <class 'complex'>


In [3]:
r1 = 5.
print("Real: ", r1, " de tipo ", type(r1))
print("Complejo: ", complex(r1), " de tipo ", type(complex(r1)))

Real:  5.0  de tipo  <class 'float'>
Complejo:  (5+0j)  de tipo  <class 'complex'>


In [4]:
r2 = 6e0
print("Real: ", r2, " de tipo ", type(r2))
print("Complejo: ", complex(r2), " de tipo ", type(complex(r2)))

Real:  6.0  de tipo  <class 'float'>
Complejo:  (6+0j)  de tipo  <class 'complex'>


In [5]:
c = 4+3j
print("Complejo: ", c, " de tipo ", type(c))

Complejo:  (4+3j)  de tipo  <class 'complex'>


In [6]:
# Funciones de variable compleja.
z = complex(input("Introduce un número complejo (no nulo): "))
print("Complejo introducido: ", z, " de tipo ", type(z))

Introduce un número complejo (no nulo): 2+3j
Complejo introducido:  (2+3j)  de tipo  <class 'complex'>


In [7]:
x = real(z)
y = imag(z)
modulo = abs(z)
argumento = angle(z)
conjugado = conj(z)
print("El número complejo ", z, " tiene parte real ", x,", parte imaginaria ", y, ", módulo ", modulo, ", argumento ", 
      argumento, " radianes, su conjugado es ", conjugado, ", su opuesto es ", -z, " y su inverso es ", z**(-1), ".")
print("Su exponencial vale ", exp(z), ".")

El número complejo  (2+3j)  tiene parte real  2.0 , parte imaginaria  3.0 , módulo  3.605551275463989 , argumento  0.982793723247329  radianes, su conjugado es  (2-3j) , su opuesto es  (-2-3j)  y su inverso es  (0.15384615384615385-0.23076923076923078j) .
Su exponencial vale  (-7.315110094901103+1.0427436562359045j) .


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Para definir un <b>vector</b> (fila) o una <b>matriz</b> utilizamos la función <span style="font-family: Courier">array()</span> cuyo argumento son los elementos del <span style="font-family: Courier">array</span>, separados por comas, encerrados entre corchetes y, en el caso de las matrices, las filas encerradas entre otros corchetes y también separadas por comas. La función <span style="font-family: Courier">print()</span> permite imprimirlos en pantalla. La <b>clase</b> a la que pertenecen (<span style="font-family: Courier">numpy.ndarray</span>) se obtiene con la función <span style="font-family: Courier">type()</span>, el <b>número de dimensiones</b> (1 en el caso de vectores y 2 en el de matrices) con la función <span style="font-family: Courier">ndim()</span> (también se puede utilizar el comando <span style="font-family: Courier">.ndim</span>), el <b>tamaño</b> (longitud del vector, o filas y columnas de las matrices) con la función <span style="font-family: Courier">shape()</span> (también se puede utilizar el comando <span style="font-family: Courier">.shape</span>), mientras que el <b>número total de elementos</b> (longitud del vector, o producto del número de filas por el de columnas de las matrices) con la función <span style="font-family: Courier">size()</span>.
     </span></div>

In [4]:
# Construcción de matrices.
A = array([[1, -2, 3], [-4, 5, -6]])
x = array([7., -8, 9])
X = array([[7, -8e0, 9]])
Y = array([[1j], [-2]])

In [5]:
print("Impresión de las matrices.")
print("A = ", A)   # matriz
print("x = ", x)   # vector 
print("X = ", X)   # matriz de tipo vector fila
print("Y = ", Y)   # matriz de tipo vector columna

Impresión de las matrices.
A =  [[ 1 -2  3]
 [-4  5 -6]]
x =  [ 7. -8.  9.]
X =  [[ 7. -8.  9.]]
Y =  [[ 0.+1.j]
 [-2.+0.j]]


In [6]:
print("Tipo de las matrices.")
print("type(A) = ", type(A))
print("type(x) = ", type(x))
print("type(X) = ", type(X))
print("type(Y) = ", type(Y))

Tipo de las matrices.
type(A) =  <class 'numpy.ndarray'>
type(x) =  <class 'numpy.ndarray'>
type(X) =  <class 'numpy.ndarray'>
type(Y) =  <class 'numpy.ndarray'>


In [7]:
print("Número de dimensiones de las matrices.")
print("ndim(A) = ", ndim(A))
print("ndim(x) = ", ndim(x))
print("ndim(X) = ", ndim(X))
print("ndim(Y) = ", ndim(Y))
print(A.ndim, x.ndim, X.ndim, Y.ndim)

Número de dimensiones de las matrices.
ndim(A) =  2
ndim(x) =  1
ndim(X) =  2
ndim(Y) =  2
2 1 2 2


In [8]:
print("Tamaño de las matrices.")
print("shape(A) = ", shape(A))
print("shape(x) = ", shape(x))
print("shape(X) = ", shape(X))
print("shape(Y) = ", shape(Y))
print(A.shape, x.shape, X.shape, Y.shape)

Tamaño de las matrices.
shape(A) =  (2, 3)
shape(x) =  (3,)
shape(X) =  (1, 3)
shape(Y) =  (2, 1)
(2, 3) (3,) (1, 3) (2, 1)


In [9]:
print("Número de elementos de las matrices.")
print("size(A) = ", size(A))
print("size(x) = ", size(x))
print("size(X) = ", size(X))
print("size(Y) = ", size(Y))
print(A.size, x.size, X.size, Y.size)

Número de elementos de las matrices.
size(A) =  6
size(x) =  3
size(X) =  3
size(Y) =  2
6 3 3 2


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Todos los elementos de un <span style="font-family: Courier">array</span> tienen el mismo tipo, que es el tipo <i>más rico</i> de entre todos sus elementos; para conocer el <b>tipo de los elementos</b> de un <span style="font-family: Courier">array</span> se usa el comando <span style="font-family: Courier">.dtype</span>. No obstante, se puede forzar el tipo de los elementos con el argumento opcional <span style="font-family: Courier">dtype=</span> de la función <span style="font-family: Courier">array()</span>.
    </span></div>

In [10]:
# Tipo de los elementos de las matrices.
print("Tipo de los elementos de las matrices.")
print("A.dtype = ", A.dtype)
print("x.dtype = ", x.dtype)
print("X.dtype = ", X.dtype)
print("Y.dtype = ", Y.dtype)

Tipo de los elementos de las matrices.
A.dtype =  int32
x.dtype =  float64
X.dtype =  float64
Y.dtype =  complex128


In [11]:
print("Matriz de tipo predefinido.")
B = array([[1, 2], [3, 4]], dtype=float)
print("B = ", B)
print("B.dtype = ", B.dtype)

Matriz de tipo predefinido.
B =  [[1. 2.]
 [3. 4.]]
B.dtype =  float64


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Se puede <b>crear</b> un <span style="font-family: Courier">array</span> lleno de 0’s con la función <span style="font-family: Courier">zeros()</span> y lleno de 1’s con la función <span style="font-family: Courier">ones()</span>; en ambos casos se debe pasar como argumento el tamaño (<span style="font-family: Courier">shape</span>) del <span style="font-family: Courier">array</span>. Para generar un <span style="font-family: Courier">array</span> con elementos aleatorios siguiendo una distribución uniforme sobre el intervalo [0, 1), la función es <span style="font-family: Courier">random.rand()</span>; esta función lleva tantos argumentos como dimensiones se quiere que tenga el <span style="font-family: Courier">array</span>, con los tamaños correspondientes. La función <span style="font-family: Courier">eye()</span> permite crear una matriz, no necesariamente cuadrada, cuyos elementos son todos 0, excepto los de la diagonal principal que valen 1; si esta función lleva un único argumento se crea una matriz cuadrada de dicho tamaño y si lleva dos una matriz rectangular; esta funcion admite un argumento opcional en la forma <span style="font-family: Courier">k=</span> que permite que la diagonal de 1’s esté <span style="font-family: Courier">k</span> posiciones por encima o por debajo (dependiendo del signo) de la diagonal principal.
    </span></div>

In [12]:
# Matrices especiales.
print("Matriz de 0's.")
C = zeros((3, 2))
print("C = ", C)
print("C.dtype = ", C.dtype)

Matriz de 0's.
C =  [[0. 0.]
 [0. 0.]
 [0. 0.]]
C.dtype =  float64


In [13]:
print("Matriz de 1's.")
D = ones((2, 3))
print("D = ", D)
print("D.dtype = ", D.dtype)

Matriz de 1's.
D =  [[1. 1. 1.]
 [1. 1. 1.]]
D.dtype =  float64


In [14]:
print("Matriz aleatoria.")
E = random.rand(3, 2)
print("E = ", E)
print("E.dtype = ", E.dtype)

Matriz aleatoria.
E =  [[0.39370624 0.74245399]
 [0.75055206 0.3004954 ]
 [0.02544803 0.80564483]]
E.dtype =  float64


In [15]:
print("Matriz de diagonal principal de 1's.")
F = eye(2, 3)
print("F = ", F)
print("F.dtype = ", F.dtype)

Matriz de diagonal principal de 1's.
F =  [[1. 0. 0.]
 [0. 1. 0.]]
F.dtype =  float64


In [16]:
print("Matriz de k-diagonal principal de 1's.")
G = eye(3, k=1)
print("G = ", G)
print("G.dtype = ", G.dtype)

Matriz de k-diagonal principal de 1's.
G =  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
G.dtype =  float64


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Las funciones <span style="font-family: Courier">arange()</span> y <span style="font-family: Courier">linspace()</span> permiten <b>crear vectores</b> (<span style="font-family: Courier">array</span> de una dimensión) <i>interpolando</i> valores intermedios entre dos extremos; los tres argumentos de la función <span style="font-family: Courier">arange</span> son el extremo inicial del intervalo (cerrado), el extremo final (abierto) y el paso de malla; los tres argumentos de la función <span style="font-family: Courier">linspace</span> son el extremo inicial del intervalo (cerrado), el extremo final (cerrado) y el número total de puntos interpolados. Se pueden <b>crear matrices</b> (<span style="font-family: Courier">array</span> de dos dimensiones) combinando estas funciones con la función <span style="font-family: Courier">reshape()</span>, cuyo primer argumento es un vector y el segundo el tamaño de la matriz que se creará.
    </span></div>

In [17]:
print("Matriz creada por interpolación.")
h = arange(0, 12, 1)   # intervalo [0,12), puntos separados por una unidad de distancia
print("h = ", h)
H = reshape(h, (3, 4))
print("H = ", H)
print("H.dtype = ", H.dtype)

Matriz creada por interpolación.
h =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
H =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
H.dtype =  int32


In [18]:
print("Matriz creada por interpolación.")
k = linspace(0, 11, 12)    # intervalo [0,11], 12 puntos totales equidistantes
print("k = ", k)
K = reshape(k, (4, 3))
print("K = ", K)
print("K.dtype = ", K.dtype)

Matriz creada por interpolación.
k =  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
K =  [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
K.dtype =  float64


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Se puede <b>acceder a los elementos</b> de un <span style="font-family: Courier">array</span> poniendo sus coordenadas entre corchetes y sabiendo que siempre se numeran desde 0. Se puede <b>acceder a más de un elemento</b> usando la notación <span style="font-family: Courier">a:b</span> o <span style="font-family: Courier">a:b:c</span> que considera todos los índices entre <span style="font-family: Courier">a</span> (incluido) y <span style="font-family: Courier">b</span> (excluido), eventualmente con salto de <span style="font-family: Courier">c</span>; la ausencia de <span style="font-family: Courier">a</span> significa que se consideran todos los índices desde el primero, y la ausencia de <span style="font-family: Courier">b</span> que se consideran todos los índices hasta el último. En el caso de matrices, la presencia de esta notación en uno de los dos índices <b>genera un vector</b>, mientras que la presencia en ambos índices <b>genera una matriz</b> (submatriz de la matriz dada).
    </span></div>

In [19]:
# Acceso a los elementos de las matrices.
print("Acceso a los elementos de las matrices.")
print("A[0, 0] = ", A[0, 0])

Acceso a los elementos de las matrices.
A[0, 0] =  1


In [20]:
print("x[1] = ", x[1])

x[1] =  -8.0


In [21]:
print("X[0, 1] = ", X[0, 1])

X[0, 1] =  -8.0


In [22]:
print("Y[1, 0] = ", Y[1, 0])

Y[1, 0] =  (-2+0j)


In [23]:
print("A[1, :] = ", A[1, :])    # elementos de la fila 1 y de todas las columnas

A[1, :] =  [-4  5 -6]


In [24]:
print("A[1:, :] = ", A[1:, :])   # elementos desde la fila 1 en adelante y de todas las columnas

A[1:, :] =  [[-4  5 -6]]


In [25]:
print("A[:, 1] = ", A[:, 1])   # elementos de todas las filas y de la columna 1

A[:, 1] =  [-2  5]


In [33]:
print("A[:, 1:2] = ", A[:, 1:2])    # no se cuenta la columna 2, son los elementos de todas las filas y de las columnas en [1,2)

A[:, 1:2] =  [[-2]
 [ 5]]


In [35]:
print("A[:1, 1:] = ", A[:1, 1:])   # elementos de las filas anteriores a la 1 y de las columnas desde la 1 en adelante

A[:1, 1:] =  [[-2  3]]


In [36]:
print("A[:, ::2] = ", A[:, ::2])   # elementos de todas las filas y desde la columna 0 hasta la 2 (sin contarla) 
                                   # con saltos de dos en dos

A[:, ::2] =  [[ 1  3]
 [-4 -6]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Para una matriz, la función <span style="font-family: Courier">transpose()</span> calcula la <b>matriz transpuesta</b> (esta función actuando sobre un vector no tiene efecto), mientras que la función <span style="font-family: Courier">conjugate()</span> solamente <b>conjuga los elementos</b>; por tanto para calcular la <b>matriz conjugada</b> de una matriz compleja hay que combinar ambas funciones.
    </span></div>

In [37]:
# Transposición y conjugación.
print("Transposición y conjugación.")
print("Transpuesta-vector: transpose(x) = ", transpose(x))

Transposición y conjugación.
Transpuesta-vector: transpose(x) =  [ 7. -8.  9.]


In [38]:
print("Transpuesta: transpose(A) = ", transpose(A))

Transpuesta: transpose(A) =  [[ 1 -4]
 [-2  5]
 [ 3 -6]]


In [39]:
print("Conjugada: conjugate(transpose(X)) = ", conjugate(transpose(X)))

Conjugada: conjugate(transpose(X)) =  [[ 7.]
 [-8.]
 [ 9.]]


In [40]:
print("Conjugada: conjugate(transpose(Y)) = ", conjugate(transpose(Y)))

Conjugada: conjugate(transpose(Y)) =  [[ 0.-1.j -2.-0.j]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Las <b>operaciones elementales</b> (<b>sumas</b> con el operador <span style="font-family: Courier">+</span>, <b>productos</b> con el operador <span style="font-family: Courier">*</span> y <b>potencias</b> con el operador <span style="font-family: Courier,">**</span>) actúan sobre los <span style="font-family: Courier">array</span> elemento a elemento (incluido el producto y la potencia). Indicamos que tanto la suma como el producto admiten dos <b>generalizaciones</b>; por un lado sumar o multiplicar una constante, en cuyo caso suma o multiplica la constante a todos sus elementos (en el caso del producto es el usual producto por escalares); por otro lado sumar o multiplicar un vector (o matriz fila) o un vector columna a una matriz, en cuyo caso lo suma o multiplica, elemento a elemento, a todas las filas o columnas de la matriz, siempre que las dimensiones lo permiten.
    <br>
    Para utilizar el <b>producto matricial</b> habitual debe utilizarse el operador <span style="font-family: Courier">@</span> y para la <b>potencia de matrices</b> la función <span style="font-family: Courier">matrix_power()</span>.
    <br>
    En cualquier caso, todos los resultados de operaciones entre matrices adopta el tipo <i>más rico</i> de todos los que intervienen en dichos cálculos.
    </span></div>

In [41]:
# Operaciones elementales.
print("Operaciones elementales.")
print("Suma: A + D = ", A + D)

Operaciones elementales.
Suma: A + D =  [[ 2. -1.  4.]
 [-3.  6. -5.]]


In [42]:
print("Suma constante: 3. + A = ", 3. + A)
print("Suma constante: -2 + x = ", -2 + x)

Suma constante: 3. + A =  [[ 4.  1.  6.]
 [-1.  8. -3.]]
Suma constante: -2 + x =  [  5. -10.   7.]


In [43]:
print("Suma vector: x + A = ", x + A)

Suma vector: x + A =  [[  8. -10.  12.]
 [  3.  -3.   3.]]


In [44]:
print("Suma matriz fila: X + A = ", X + A)

Suma matriz fila: X + A =  [[  8. -10.  12.]
 [  3.  -3.   3.]]


In [45]:
print("Suma matriz columna: Y + A = ", Y + A)

Suma matriz columna: Y + A =  [[ 1.+1.j -2.+1.j  3.+1.j]
 [-6.+0.j  3.+0.j -8.+0.j]]


In [46]:
print("Producto-elemento: A*D = ", A*D)

Producto-elemento: A*D =  [[ 1. -2.  3.]
 [-4.  5. -6.]]


In [47]:
print("Producto escalares: 3*A = ", 3*A)

Producto escalares: 3*A =  [[  3  -6   9]
 [-12  15 -18]]


In [48]:
print("Producto vector: x*A = ", x*A)

Producto vector: x*A =  [[  7.  16.  27.]
 [-28. -40. -54.]]


In [49]:
print("Producto matriz fila: X*A = ", X*A)

Producto matriz fila: X*A =  [[  7.  16.  27.]
 [-28. -40. -54.]]


In [50]:
print("Producto matriz columna: Y*A = ", Y*A)

Producto matriz columna: Y*A =  [[  0.+1.j  -0.-2.j   0.+3.j]
 [  8.-0.j -10.+0.j  12.-0.j]]


In [51]:
print("Producto: A@H = ", A@H)

Producto: A@H =  [[ 16  18  20  22]
 [-28 -33 -38 -43]]


In [52]:
print("Potencia-elemento: A**3 = ", A**3)

Potencia-elemento: A**3 =  [[   1   -8   27]
 [ -64  125 -216]]


In [53]:
print("Potencia: matrix_power(B, 2) = ", matrix_power(B, 2))

Potencia: matrix_power(B, 2) =  [[ 7. 10.]
 [15. 22.]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Las funciones <span style="font-family: Courier">tril()</span> y <span style="font-family: Courier">triu()</span> extraen la parte <b>triangular inferior</b> y <b>superior</b>, respectivamente, de la matriz que se da como argumento; estas funciones  admiten un argumento opcional <span style="font-family: Courier">k=</span>, que puede ser positivo o negativo, que permite añadir o suprimir extradiagonales.
    <br>
    Cuando el argumento de estas funciones es un vector, se construye una matriz cuadrada triangular con el vector dado
como fila de dicha matriz.
    </span></div>

In [54]:
# Matrices triangulares.
print("Matrices triangulares:")
print("tril(A) = ", tril(A))
print("tril(A, k=1) = ", tril(A, k=1))
print("tril(A, k=-1) = ", tril(A, k=-1))

Matrices triangulares:
tril(A) =  [[ 1  0  0]
 [-4  5  0]]
tril(A, k=1) =  [[ 1 -2  0]
 [-4  5 -6]]
tril(A, k=-1) =  [[ 0  0  0]
 [-4  0  0]]


In [55]:
print("triu(A) = ", triu(A))
print("triu(A, k=1) = ", triu(A, k=1))
print("triu(A, k=-1) = ", triu(A, k=-1))

triu(A) =  [[ 1 -2  3]
 [ 0  5 -6]]
triu(A, k=1) =  [[ 0 -2  3]
 [ 0  0 -6]]
triu(A, k=-1) =  [[ 1 -2  3]
 [-4  5 -6]]


In [56]:
print("tril(x) = ", tril(x))
print("triu(x) = ", triu(x))

tril(x) =  [[ 7.  0.  0.]
 [ 7. -8.  0.]
 [ 7. -8.  9.]]
triu(x) =  [[ 7. -8.  9.]
 [ 0. -8.  9.]
 [ 0.  0.  9.]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Ciertas <b>funciones usuales</b> actúan sobre <span style="font-family: Courier">array</span> de una forma predecible; será útil comprobar esto considerando tanto vectores como matrices (reales o complejas) y viendo como se transforman mediante la función <span style="font-family: Courier">abs()</span>, cuyo argumento es el <span style="font-family: Courier">array</span> al que se le calcularán los valores absolutos o módulos de sus elementos, y la función <span style="font-family: Courier">sum()</span> cuyo argumento es el <span style="font-family: Courier">array</span> cuyos elementos se sumarán; en el caso de matrices, esta última función admite un argumento opcional en la forma <span style="font-family: Courier">axis=0</span> o <span style="font-family: Courier">axis=1</span>, que permite hacer la suma por columnas o por filas, dando como resultado un vector. Un comportamiento totalmente análogo, incluido el argumento opcional, tienen lss funciones <span style="font-family: Courier">max()</span> y <span style="font-family: Courier">min()</span>.
    </span></div>

In [57]:
# Funciones usuales.
print("Funciones usuales.")
print("abs(A) = ", abs(A))
print("abs(x) = ", abs(x))
print("abs(X) = ", abs(X))
print("abs(Y) = ", abs(Y))

Funciones usuales.
abs(A) =  [[1 2 3]
 [4 5 6]]
abs(x) =  [7. 8. 9.]
abs(X) =  [[7. 8. 9.]]
abs(Y) =  [[1.]
 [2.]]


In [58]:
print("sum(A) = ", sum(A))
print("sum(A, axis=0) = ", sum(A, axis=0))
print("sum(A, axis=1) = ", sum(A, axis=1))

sum(A) =  -3
sum(A, axis=0) =  [-3  3 -3]
sum(A, axis=1) =  [ 2 -5]


In [59]:
print("max(A) = ", max(A))
print("max(A, axis=0) = ", max(A, axis=0))
print("max(A, axis=1) = ", max(A, axis=1))

max(A) =  5
max(A, axis=0) =  [1 5 3]
max(A, axis=1) =  [3 5]


In [60]:
print("min(A) = ", min(A))
print("min(A, axis=0) = ", min(A, axis=0))
print("min(A, axis=1) = ", min(A, axis=1))

min(A) =  -6
min(A, axis=0) =  [-4 -2 -6]
min(A, axis=1) =  [-2 -6]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    La función <span style="font-family: Courier">diagflat()</span> permite construir <b>matrices diagonales</b> a partir de los elementos de un vector o de una matriz, que se da como argumento; admite un argumento opcional <span style="font-family: Courier">k=</span> que coloca los elementos <span style="font-family: Courier">k</span> diagonales por arriba o por abajo, dependiendo del signo, de la diagonal principal.
    <br>
    Recíprocamente, cuando la función <span style="font-family: Courier">diag()</span> tiene como argumento una matriz, se extrae en un vector la diagonal principal de la misma; admite el mismo argumento opcional <span style="font-family: Courier">k=</span> con un objetivo análogo. Cuando esta función tienen como argumento un vector el efecto es el mismo que la función anterior.
    </span></div>

In [61]:
print("Matrices diagonales.")
print("diagflat(x) = ", diagflat(x))

Matrices diagonales.
diagflat(x) =  [[ 7.  0.  0.]
 [ 0. -8.  0.]
 [ 0.  0.  9.]]


In [62]:
print("diagflat(Y, k=1) = ", diagflat(Y, k=1))

diagflat(Y, k=1) =  [[ 0.+0.j  0.+1.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]]


In [63]:
print("diagflat(A, k=-1) = ", diagflat(A, k=-1))

diagflat(A, k=-1) =  [[ 0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0]
 [ 0 -2  0  0  0  0  0]
 [ 0  0  3  0  0  0  0]
 [ 0  0  0 -4  0  0  0]
 [ 0  0  0  0  5  0  0]
 [ 0  0  0  0  0 -6  0]]


In [64]:
print("diag(A) = ", diag(A))

diag(A) =  [1 5]


In [65]:
print("diag(A, k=1) = ", diag(A, k=1))

diag(A, k=1) =  [-2 -6]


In [66]:
print("diag(Y) = ", diag(Y))

diag(Y) =  [0.+1.j]


In [67]:
print("diag(x) = ", diag(x))

diag(x) =  [[ 7.  0.  0.]
 [ 0. -8.  0.]
 [ 0.  0.  9.]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Es también es posible <b>concatenar matrices</b>, tanto horizontal, como verticalmente, con las funciones
<span style="font-family: Courier">hstack()</span> y <span style="font-family: Courier">vstack()</span>; el argumento de estas funciones es la tupla formada por las matrices que se quieren concatenar, cuyas dimensiones deben permitir esta manipulación. También aquí todos los resultados de manipulaciones entre matrices adopta el tipo <i>más rico</i> de todos los que intervienen en dichas manipulaciones.
    </span></div>

In [68]:
print("Matrices concatenadas.")
print("vstack([A, D]) = ", vstack([A, D]))

Matrices concatenadas.
vstack([A, D]) =  [[ 1. -2.  3.]
 [-4.  5. -6.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [69]:
print("hstack([A, B]) = ", hstack([A, B]))

hstack([A, B]) =  [[ 1. -2.  3.  1.  2.]
 [-4.  5. -6.  3.  4.]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Generar una matriz de tamaño 20, que sea tridiagonal con elementos diagonales iguales a 2 y elementos sub-diagonales y supra-diagonales iguales a -1.
    </span></div>

In [2]:
# Ejercicio 1.
print("Ejercicio 1.")
A = 2*eye(20) - eye(20, k=1) - eye(20, k=-1)
print("A = ", A)

Ejercicio 1.
A =  [[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Dada la matriz $A = \left( \begin{array}{cc} 1 & 2 \\ 3 & 4 \end{array} \right)$, construir las matrices $B = \left( \begin{array}{c|c} A & 2\,A \\ \hline 3\,A & 4\,A \end{array} \right)$ y $C = \left( \begin{array}{c|c|c} A & I & \\ \hline I & A & I \\ \hline & I & A \end{array} \right)$. Con la ayuda de la función <span style="font-family: Courier">det()</span>, cuyo único argumento es una matriz, calcular los determinantes de las matrices anteriores.
    </span></div>

In [5]:
# Ejercicio 2.
print("Ejercicio 2.")
A = array ([[1,2], [3,4]])
print("A = ", A)
print("det(A) = ", det(A))
B = vstack([hstack([A, 2*A]), hstack([3*A, 4*A])])
print("B = [[A,2A],[3A,4A]] = \n", B)
print("det(B) = ", det(B))
C = vstack([hstack([A, eye(2), zeros((2,2))]), hstack([eye(2), A, eye(2)]), hstack([zeros((2,2)), eye(2), A])])
print("C = [[A,I,0],[I,A,I],[0,I,A]] = \n", C)
print("det(C) = ", det(C))

Ejercicio 2.
A =  [[1 2]
 [3 4]]
det(A) =  -2.0000000000000004
B = [[A,2A],[3A,4A]] = 
 [[ 1  2  2  4]
 [ 3  4  6  8]
 [ 3  6  4  8]
 [ 9 12 12 16]]
det(B) =  16.000000000000007
C = [[A,I,0],[I,A,I],[0,I,A]] = 
 [[1. 2. 1. 0. 0. 0.]
 [3. 4. 0. 1. 0. 0.]
 [1. 0. 1. 2. 1. 0.]
 [0. 1. 3. 4. 0. 1.]
 [0. 0. 1. 0. 1. 2.]
 [0. 0. 0. 1. 3. 4.]]
det(C) =  99.99999999999996


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3.</b></span> Construir una matriz $A=(a_{i,j})\in\mathcal{M}_{10}(\mathbb{R})$ tal que $a_{i,j}=10\,(i-1)+j$, para todo $i,j=1,2,\ldots,10$. Construir también las matrices $B,C\in\mathcal{M}_{10}(\mathbb{R})$ que coinciden con $A$, excepto que en $B$ permutan entre sí las filas y columnas segunda y quinta, y en $C$ a la quinta fila de $A$ se le suma 3 veces la segunda fila.
    </span></div>

In [8]:
# Ejercicio 3.
print("Ejercicio 3.")
A = reshape(arange(1, 101, 1, dtype=float), (10, 10)) 
print("A = \n", A)
B = array(A)    # B es una copia del array A
B[[1,4], :] = B[[4,1], :] #las filas 2 y 5 van a ser las filas 5 y 2 de la antigua.
B[:, [1,4]] = B[:, [4,1]] #Las columnas 2 y 5 van a ser las columnas 5 y 2 de la antigua.
print("B = \n", B)
C = array(A)
C[4, :] += 3*C[1, :] #A la quinta fila se le suma 3 veces la segunda.
#Similar a poner: C[4, :] = C[4, :] + 3*C[1, :]
print("C = \n", C)

Ejercicio 3.
A = 
 [[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.  36.  37.  38.  39.  40.]
 [ 41.  42.  43.  44.  45.  46.  47.  48.  49.  50.]
 [ 51.  52.  53.  54.  55.  56.  57.  58.  59.  60.]
 [ 61.  62.  63.  64.  65.  66.  67.  68.  69.  70.]
 [ 71.  72.  73.  74.  75.  76.  77.  78.  79.  80.]
 [ 81.  82.  83.  84.  85.  86.  87.  88.  89.  90.]
 [ 91.  92.  93.  94.  95.  96.  97.  98.  99. 100.]]
B = 
 [[  1.   5.   3.   4.   2.   6.   7.   8.   9.  10.]
 [ 41.  45.  43.  44.  42.  46.  47.  48.  49.  50.]
 [ 21.  25.  23.  24.  22.  26.  27.  28.  29.  30.]
 [ 31.  35.  33.  34.  32.  36.  37.  38.  39.  40.]
 [ 11.  15.  13.  14.  12.  16.  17.  18.  19.  20.]
 [ 51.  55.  53.  54.  52.  56.  57.  58.  59.  60.]
 [ 61.  65.  63.  64.  62.  66.  67.  68.  69.  70.]
 [ 71.  75.  73.  74.  72.  76.  77.  78.  79.  80.]
 [ 81.  85.  83.  84

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4.</b></span> Se llama <b>matriz de Hilbert de orden $n$</b> a la matriz $H=(h_{i,j})\in\mathcal{M}(\mathbb{R})$ tal que $h_{i,j}=\frac{1}{i+j-1}$, para todo $i,j=1,2,\ldots,n$. Construir e imprimir una matriz de Hilbert de orden 5, así como todas sus submatrices principales (que son también matrices de Hilbert); calcular también el determinante de estas submatrices.
    </span></div>

In [ ]:
# Ejercicio 4.
print("Ejercicio 4.")
n = 5
H = zeros((n,n))
for i in range(n):
    for j in range(n):
        H[i, j] = 1/(1+i+j)  #(i+1 + j+1 - 1  = i+j+1, pues las posiciones 
print("H = \n", H)
for k in range(n):
    print("Submatriz principal de orden: ", k+1)
    print("H^(", k+1, ") = \n", H[:k+1, :k+1]) #filas y columnas desde 0 hasta k+1. Submatrices principales.
    print("det H^(", k+1, ") = ",  det(H[:k+1, :k+1])) #El determinante de las submatrices va tendiendo a 0

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 5.</b></span> Se llama <b>matriz de Vandermonde de orden $n$</b> a la matriz $V=(v_{i,j})\in\mathcal{M}(\mathbb{K})$ tal que $v_{i,j}={\alpha_i}^{j-1}$, para todo $i,j=1,2,\ldots,n$, siendo $\alpha_i\in\mathbb{K}$, para $i=1,2,\ldots,n$; en el caso en que $\alpha_i=i$, construir e imprimir una matriz de Vandermonde de orden 5.
    <br>
    Para suprimir líneas (filas o columnas) de una matriz, se puede utilizar la función <span style="font-family: Courier">delete()</span>, cuyos tres argumentos son una matriz, la(s) línea(s) que se quieren suprimir, y <span style="font-family: Courier">axis=</span> para indicar si se suprimen filas o columnas. Por otro lado, la función <span style="font-family: Courier">inv()</span>, cuyo único argumento es una matriz, calcula la inversa de la matriz dada (supuesta regular).
    <br>
    Construir la matriz de cofactores de la matriz de Vandermonde anterior y comprobar que la transpuesta de la misma, dividida por su determinante, es la inversa.
</span>

In [9]:
# Ejercicio 5.
print("Ejercicio 5.")
n = 5
V = zeros((n,n))
for i in range(n):
    for j in range(n):
        V[i, j] = (i+1)**j   #(i+1)^(j+1 -1) Subíndices de las matrices en python
print("V = \n", V)
cofV = zeros((n,n))
for i in range(n):
    for j in range(n):
        cofV[i, j] = det(delete(delete(V, j, axis=1), i, axis=0))*((-1)**(i+1 +j+1)) #i+1, j+1 pues son las columnas i,j{0..5}
print("cof(V) = \n", cofV)
print("V^(-1) = \n", inv(V))
print("det(V)^(-1)*cof(V)^t =\n ", transpose(cofV)/det(V))
print("Comprobación: ", max(abs(inv(V)-transpose(cofV)/det(V))))

Ejercicio 5.
V = 
 [[  1.   1.   1.   1.   1.]
 [  1.   2.   4.   8.  16.]
 [  1.   3.   9.  27.  81.]
 [  1.   4.  16.  64. 256.]
 [  1.   5.  25. 125. 625.]]
cof(V) = 
 [[ 1440. -1848.   852.  -168.    12.]
 [-2880.  5136. -2832.   624.   -48.]
 [ 2880. -5616.  3528.  -864.    72.]
 [-1440.  2928. -1968.   528.   -48.]
 [  288.  -600.   420.  -120.    12.]]
V^(-1) = 
 [[  5.         -10.          10.          -5.           1.        ]
 [ -6.41666667  17.83333333 -19.5         10.16666667  -2.08333333]
 [  2.95833333  -9.83333333  12.25        -6.83333333   1.45833333]
 [ -0.58333333   2.16666667  -3.           1.83333333  -0.41666667]
 [  0.04166667  -0.16666667   0.25        -0.16666667   0.04166667]]
det(V)^(-1)*cof(V)^t =
  [[  5.         -10.          10.          -5.           1.        ]
 [ -6.41666667  17.83333333 -19.5         10.16666667  -2.08333333]
 [  2.95833333  -9.83333333  12.25        -6.83333333   1.45833333]
 [ -0.58333333   2.16666667  -3.           1.83333333  -0